### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by argosk** [maciejcieslar/instagrambot#4]
Hi,
first of all, congrats for the great work. I'm trying your app but I'm getting an Error when I run the app:

> Failed to like/follow/comment.
Error: Evaluation failed: TypeError: Cannot read property 'parent' of null
    at <anonymous>:13:18
    at ExecutionContext.evaluateHandle (/home/emilio/Desktop/instagrambot/node_modules/puppeteer/lib/ExecutionContext.js:88:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

Any idea what it could be?

**Comment by rosariogueli** [comment]
Yup, there's something wrong, I also get the Error: Evaluation failed: TypeError: Cannot read property 'parent' of null
I will take a look at it myself and update this space when I manage to fix it.

**Comment by bdcuck** [comment]
> 
> 
> Yup, there's something wrong, I also get the Error: Evaluation failed: TypeError: Cannot read property 'parent' of null
> I will take a look at it myself and update this space when I manage to fix it.

Selectors for like buttons etc also don't seem to be working. I havent been able to fix it myself yet but your fix helped with  Cannot read property 'parent' of null

For the likes I get similar errors, alternating between parent of null and selector errors so the fix is probably similar:

`https://www.instagram.com/p/someLink/
Failed to like/follow/comment.
Error: Evaluation failed: TypeError: Cannot read property 'parent' of null
    at <anonymous>:13:18
    at ExecutionContext.evaluateHandle (C:\Users\Bd\Documents\Code\JS\instagrambot\node_modules\puppeteer\lib\ExecutionContext.js:88:13)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
https://www.instagram.com/p/someOtherLink/
Failed to like/follow/comment.
Error: waiting for selector "button[data-scraper-like="likeHeart"]" failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (C:\Users\Bd\Documents\Code\JS\instagrambot\node_modules\puppeteer\lib\FrameManager.js:841:60)
    at listOnTimeout (timers.js:327:15)
    at processTimers (timers.js:271:5)`

**Comment by rosariogueli** [comment]
Yeah I didn't take a look at those yet, I only fixed what I needed for the comment function. When I get a little more time i will be happy to fix it.
